export {HomePage} from './HomePage/ui/HomePage'
export {MenuPage} from './MenuPage/ui/MenuPage'
export {MenuPage2} from './MenuPage2/ui/MenuPage2'
export {HistoryPage} from './HistoryPage/ui/HistoryPage'
export {Dishes} from './Dishes/ui/Dishes'
export {GaleryDishesPage} from './GaleryDishesPage/ui/GaleryDishesPage'
export {СhefsPage} from './СhefsPage/ui/СhefsPage'
export {AboutPage} from './ReviewsPage/ui/AboutPage'